Scrapping Tasks
mhammadsani/training pull request #3
Opened 2023-08-31 23:28 UTC by mhammadsani

2023-09-05 12:11 UTC, FatimaSaleem21 commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/codedamn.py
> +            'https://codedamn.com/login',
Use constant for login URL

2023-09-05 12:11 UTC, FatimaSaleem21 commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/codedamn.py
> +        self.solve_captcha()
Please use `wait()` here

2023-09-05 12:11 UTC, FatimaSaleem21 commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/codedamn.py
> +        return driver
Please move these functions above the scrapper method

2023-09-05 12:11 UTC, FatimaSaleem21 commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/codedamn.py
> +    def expand_buttons(self, driver):
Please move all helper functions to a separate file.

2023-09-05 12:11 UTC, FatimaSaleem21 commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/codedamn.py
> +    def solve_captcha(self):
We can remove this function

2023-09-05 12:11 UTC, FatimaSaleem21 commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/codedamn.py
> +        time.sleep(2)
At some instances, we are using `wait()` function and on other instances we are using `time.sleep()`. Isnt it better to use `time.sleep()` directly at all places?

2023-09-05 13:35 UTC, FatimaSaleem21 requested changes

2023-09-05 13:35 UTC, FatimaSaleem21 commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/utils.py
> +    time.sleep(seconds)
Instead of defining a function for wait, we can use `time.sleep()` directly

2023-09-05 13:35 UTC, FatimaSaleem21 commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/utils.py
> +        click_button(driver, chr(asci_number))
What is the reason for these random range values in loop?

2023-09-05 13:35 UTC, FatimaSaleem21 commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/utils.py
> +    except Exception as e:
We can use a better alias than `e`

2023-09-05 13:35 UTC, FatimaSaleem21 commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/utils.py
> +        wait(10)
We can use `time.sleep()`

2023-09-05 13:35 UTC, FatimaSaleem21 commented on scrapping_tasks/educative/educative/items.py
> +                  if part.strip() not in ['', '·']]
We can improve the indentation

2023-09-11 07:19 UTC, mhammadsani commented on scrapping_tasks/codedamn_courses_scraper/codedamn_courses_scraper/spiders/utils.py
> +        click_button(driver, chr(asci_number))
These numbers are helping find the classes names, so program can select the appropriate content from the page.

2023-09-21 12:20 UTC, FatimaSaleem21 approved these changes

2023-09-22 07:32 UTC, merged